name: Haskell build
on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3.0.2
      - name: setup haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: 9.2.4
          cabal-version: 3.6.2.0
      - name: freeze Cabal plan
        run: |
          cd haskell
          cabal freeze
      - name: cache Cabal build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-build-env.outputs.cabal-store }}
            dist-newstyle
          key: cabal-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: cabal-
      - name: test
        run: |
          cd haskell
          cabal test
