name: Haskell build
on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3.0.2
      - name: setup haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: 9.2.4
          cabal-version: 3.6.2.0
      - name: configure Cabal
        run: |
          cd haskell
          cabal configure --enable-tests --enable-benchmarks --enable-documentation --test-show-details=direct --write-ghc-environment-files=always
      - name: freeze Cabal plan
        run: |
          cd haskell
          cabal freeze
      - name: cache Cabal build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            haskell/dist-newstyle
          key: cabal-${{ hashFiles('haskell/cabal.project.freeze') }}
      - name: build
        run: |
          cd haskell
          cabal build all
      - name: test
        run: |
          cd haskell
          cabal test all --test-show-details=direct
