name: Scala build
on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3.0.2
      - name: setup java
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17
          distribution: temurin
          cache: sbt
      - name: test
        run: |
          cd scala
          sbt test
